// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValeoBot;

namespace ValeoBot.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191027180645_AddDoctorEntity")]
    partial class AddDoctorEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ValeoBot.Data.Entities.Order", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("Category");

                    b.Property<long>("ChatId");

                    b.Property<string>("DoctorId");

                    b.Property<string>("Time");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ValeoBot.Data.Entities.Registration", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("AuthServiceToken");

                    b.Property<int?>("RegistrationMessageId");

                    b.Property<DateTime>("Time");

                    b.HasKey("Id");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("ValeoBot.Data.Entities.ValeoUser", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsAdmin");

                    b.Property<string>("LastName");

                    b.Property<long?>("LastOrderId");

                    b.Property<string>("Nickname");

                    b.HasKey("Id");

                    b.HasIndex("LastOrderId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ValeoBot.Data.Entities.ValeoUser", b =>
                {
                    b.HasOne("ValeoBot.Data.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("LastOrderId");
                });
#pragma warning restore 612, 618
        }
    }
}
