// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValeoBot;

namespace ValeoBot.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ValeoBot.Data.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("ChatId");

                    b.Property<string>("DoctorID");

                    b.Property<string>("PatientName");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Time");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ValeoBot.Data.Entities.User", b =>
                {
                    b.Property<long>("Id");

                    b.Property<bool>("IsAdmin");

                    b.Property<long?>("LastOrderId");

                    b.Property<string>("Nickname");

                    b.HasKey("Id");

                    b.HasIndex("LastOrderId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ValeoBot.Data.Entities.User", b =>
                {
                    b.HasOne("ValeoBot.Data.Entities.Order", "Order")
                        .WithMany("Users")
                        .HasForeignKey("LastOrderId");
                });
#pragma warning restore 612, 618
        }
    }
}
